[project]
name = "vmware-rpc"
version = "0.1.0"
description = "A Discord RPC for VMWare"
readme = "README.md"
authors = [
    { name = "OReactko", email = "son682014@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dissect-hypervisor>=3.21",
    "prompt-toolkit>=3.0.53",
    "psutil>=7.2.2",
    "pypresence>=4.6.2",
    "requests>=2.34.2",
]

[project.scripts]
vmware-rpc = "vmware_rpc:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
